/*
 * notekit_score_lilac.c
 *
 *  Created on: Oct 8, 2025
 *      Author: m-ren
 */

#include "NoteKit.h"
// --- 楽譜データの定義 ---
// パート1：主旋律
const ScoreNote part1_melody[] = {

	/* ------------------ 1 ------------------ */
    { PITCH_F, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_G, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_C, OCTAVE_5, DURATION_SIXTEENTH },
    { PITCH_G, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_F, OCTAVE_4, DURATION_EIGHTH },

    { PITCH_G, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_C, OCTAVE_5, DURATION_SIXTEENTH },
    { PITCH_F, OCTAVE_5, DURATION_SIXTEENTH },
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_C, OCTAVE_5, DURATION_SIXTEENTH },
    { PITCH_F, OCTAVE_4, DURATION_QUARTER},

	/* ------------------ 2 ------------------ */
    { PITCH_F, OCTAVE_4, DURATION_SIXTEENTH},
    { PITCH_G, OCTAVE_4, DURATION_SIXTEENTH},
    { PITCH_AS, OCTAVE_4, DURATION_EIGHTH},
    { PITCH_C, OCTAVE_5, DURATION_EIGHTH},

    { PITCH_DS, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_F, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_G, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_F, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_DS, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_D, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_C, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH},

	/* ------------------ 3 ------------------ */
    { PITCH_G, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_AS, OCTAVE_4, DURATION_EIGHTH},
    { PITCH_G, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_F, OCTAVE_5, DURATION_QUARTER},
    { PITCH_DS, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_D, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_AS, OCTAVE_4, DURATION_EIGHTH},

	/* ------------------ 4 ------------------ */
    { PITCH_REST, OCTAVE_5, DURATION_HALF},
    { PITCH_C, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_REST, OCTAVE_4, DURATION_SIXTEENTH},
    { PITCH_A, OCTAVE_4, DURATION_SIXTEENTH},
    { PITCH_REST, OCTAVE_4, DURATION_QUARTER},

	/* ------------------ 5 ------------------ */
    { PITCH_F, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_G, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_C, OCTAVE_5, DURATION_SIXTEENTH },
    { PITCH_G, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_F, OCTAVE_4, DURATION_EIGHTH },

    { PITCH_G, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_C, OCTAVE_5, DURATION_SIXTEENTH },
    { PITCH_F, OCTAVE_5, DURATION_SIXTEENTH },
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_C, OCTAVE_5, DURATION_SIXTEENTH },
    { PITCH_F, OCTAVE_4, DURATION_QUARTER},

	/* ------------------ 6 ------------------ */
    { PITCH_F, OCTAVE_4, DURATION_SIXTEENTH},
    { PITCH_G, OCTAVE_4, DURATION_SIXTEENTH},
    { PITCH_AS, OCTAVE_4, DURATION_EIGHTH},
    { PITCH_C, OCTAVE_5, DURATION_EIGHTH},

    { PITCH_DS, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_F, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_G, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_F, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_DS, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_D, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_C, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH},

	/* ------------------ 7 ------------------ */
    { PITCH_AS, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_AS, OCTAVE_4, DURATION_EIGHTH},
    { PITCH_C, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_F, OCTAVE_4, DURATION_EIGHTH},
    { PITCH_F, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_F, OCTAVE_4, DURATION_EIGHTH},
    { PITCH_AS, OCTAVE_4, DURATION_EIGHTH},
    { PITCH_F, OCTAVE_4, DURATION_EIGHTH},

	/* ------------------ 8 ------------------ */
    { PITCH_REST, OCTAVE_4, DURATION_QUARTER},
    { PITCH_REST, OCTAVE_4, DURATION_EIGHTH},
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH},
    { PITCH_C, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_F, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_REST, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_AS, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_REST, OCTAVE_5, DURATION_QUARTER},

	/* ------------------ 9 ------------------ */
    { PITCH_F, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_G, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_C, OCTAVE_5, DURATION_SIXTEENTH },
    { PITCH_G, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_F, OCTAVE_4, DURATION_EIGHTH },

    { PITCH_G, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_C, OCTAVE_5, DURATION_SIXTEENTH },
    { PITCH_F, OCTAVE_5, DURATION_SIXTEENTH },
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_C, OCTAVE_5, DURATION_SIXTEENTH },
    { PITCH_F, OCTAVE_4, DURATION_QUARTER},

	/* ------------------ 10 ------------------ */
    { PITCH_F, OCTAVE_4, DURATION_SIXTEENTH},
    { PITCH_G, OCTAVE_4, DURATION_SIXTEENTH},
    { PITCH_AS, OCTAVE_4, DURATION_EIGHTH},
    { PITCH_C, OCTAVE_5, DURATION_EIGHTH},

    { PITCH_DS, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_F, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_G, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_F, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_DS, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_D, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_C, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH},

	/* ------------------ 11 ------------------ */
    { PITCH_G, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_AS, OCTAVE_4, DURATION_EIGHTH},
    { PITCH_G, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_F, OCTAVE_5, DURATION_QUARTER},
    { PITCH_DS, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_D, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_AS, OCTAVE_4, DURATION_DOTTED_QUARTER},

	/* ------------------ 12 ------------------ */
    { PITCH_F, OCTAVE_4, DURATION_SIXTEENTH},
    { PITCH_G, OCTAVE_4, DURATION_SIXTEENTH},
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH},
    { PITCH_C, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_D, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_C, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH},
    { PITCH_C, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_D, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_AS, OCTAVE_4, DURATION_EIGHTH},

	/* ------------------ 13 ------------------ */
    { PITCH_F, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_G, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_C, OCTAVE_5, DURATION_SIXTEENTH },
    { PITCH_G, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_F, OCTAVE_4, DURATION_EIGHTH },

    { PITCH_G, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_C, OCTAVE_5, DURATION_SIXTEENTH },
    { PITCH_F, OCTAVE_5, DURATION_SIXTEENTH },
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_C, OCTAVE_5, DURATION_SIXTEENTH },
    { PITCH_F, OCTAVE_4, DURATION_QUARTER},

	/* ------------------ 14 ------------------ */
    { PITCH_F, OCTAVE_4, DURATION_SIXTEENTH},
    { PITCH_G, OCTAVE_4, DURATION_SIXTEENTH},
    { PITCH_AS, OCTAVE_4, DURATION_EIGHTH},
    { PITCH_C, OCTAVE_5, DURATION_EIGHTH},

    { PITCH_DS, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_F, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_G, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_F, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_DS, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_D, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_C, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH},

	/* ------------------ 15 ------------------ */
    { PITCH_G, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_AS, OCTAVE_4, DURATION_EIGHTH},
    { PITCH_G, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_F, OCTAVE_5, DURATION_QUARTER},
    { PITCH_DS, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_D, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_AS, OCTAVE_4, DURATION_DOTTED_QUARTER},

	/* ------------------ 16 ------------------ */
    { PITCH_REST, OCTAVE_4, DURATION_SIXTEENTH},
    { PITCH_F, OCTAVE_4, DURATION_SIXTEENTH},
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH},
    { PITCH_C, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_F, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_F, OCTAVE_4, DURATION_SIXTEENTH},
    { PITCH_AS, OCTAVE_4, DURATION_SIXTEENTH},
    { PITCH_C, OCTAVE_5, DURATION_SIXTEENTH},
    { PITCH_F, OCTAVE_5, DURATION_QUARTER},
};
const int part1_len = sizeof(part1_melody) / sizeof(part1_melody[0]);

// パート2：ベースライン
const ScoreNote part2_bass[] = {

	/* ------------------ 1 ------------------ */
	{ PITCH_D, OCTAVE_4, DURATION_EIGHTH },
	{ PITCH_REST, OCTAVE_4, DURATION_EIGHTH },

    { PITCH_REST, OCTAVE_4, DURATION_QUARTER },
    { PITCH_D, OCTAVE_4, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_D, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_REST, OCTAVE_4, DURATION_EIGHTH },
    { PITCH_C, OCTAVE_4, DURATION_EIGHTH },

	/* ------------------ 2 ------------------ */
    { PITCH_REST, OCTAVE_4, DURATION_EIGHTH },

    { PITCH_C, OCTAVE_4, DURATION_EIGHTH },

    { PITCH_C, OCTAVE_4, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_4, DURATION_EIGHTH },

    { PITCH_C, OCTAVE_4, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_4, DURATION_EIGHTH },

    { PITCH_REST, OCTAVE_4, DURATION_QUARTER },

	/* ------------------ 3 ------------------ */
    { PITCH_AS, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_3, DURATION_EIGHTH },

    { PITCH_REST, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_AS, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_AS, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_3, DURATION_SIXTEENTH },
    { PITCH_AS, OCTAVE_3, DURATION_SIXTEENTH },
    { PITCH_REST, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_F, OCTAVE_3, DURATION_EIGHTH },

	/* ------------------ 4 ------------------ */
    { PITCH_REST, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_F, OCTAVE_3, DURATION_EIGHTH },

    { PITCH_F, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_3, DURATION_EIGHTH },

    { PITCH_F, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_3, DURATION_SIXTEENTH },
    { PITCH_A, OCTAVE_3, DURATION_SIXTEENTH },
    { PITCH_REST, OCTAVE_3, DURATION_QUARTER },

	/* ------------------ 5 ------------------ */
	{ PITCH_D, OCTAVE_4, DURATION_EIGHTH },
	{ PITCH_REST, OCTAVE_4, DURATION_EIGHTH },

    { PITCH_REST, OCTAVE_4, DURATION_QUARTER },
    { PITCH_D, OCTAVE_4, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_D, OCTAVE_4, DURATION_SIXTEENTH },
    { PITCH_REST, OCTAVE_4, DURATION_EIGHTH },
    { PITCH_C, OCTAVE_4, DURATION_EIGHTH },

	/* ------------------ 6 ------------------ */
    { PITCH_REST, OCTAVE_4, DURATION_EIGHTH },

    { PITCH_C, OCTAVE_4, DURATION_EIGHTH },

    { PITCH_C, OCTAVE_4, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_4, DURATION_EIGHTH },

    { PITCH_C, OCTAVE_4, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_4, DURATION_EIGHTH },

    { PITCH_REST, OCTAVE_4, DURATION_QUARTER },

	/* ------------------ 7 ------------------ */
    { PITCH_AS, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_3, DURATION_EIGHTH },

    { PITCH_REST, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_AS, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_AS, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_3, DURATION_SIXTEENTH },
    { PITCH_AS, OCTAVE_3, DURATION_SIXTEENTH },
    { PITCH_REST, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_F, OCTAVE_3, DURATION_EIGHTH },

	/* ------------------ 8 ------------------ */
    { PITCH_REST, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_F, OCTAVE_3, DURATION_EIGHTH },

    { PITCH_F, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_3, DURATION_EIGHTH },

    { PITCH_F, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_3, DURATION_SIXTEENTH },
    { PITCH_A, OCTAVE_3, DURATION_SIXTEENTH },
    { PITCH_REST, OCTAVE_3, DURATION_QUARTER },

	/* ------------------ 9 ------------------ */
    { PITCH_REST, OCTAVE_3, DURATION_WHOLE },

	/* ------------------ 10 ------------------ */
    { PITCH_REST, OCTAVE_3, DURATION_WHOLE },

	/* ------------------ 11 ------------------ */
    { PITCH_DS, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_REST, OCTAVE_4, DURATION_EIGHTH},
    { PITCH_REST, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_AS, OCTAVE_4, DURATION_QUARTER},
    { PITCH_REST, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_REST, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_F, OCTAVE_4, DURATION_DOTTED_QUARTER},

	/* ------------------ 12 ------------------ */
    { PITCH_F, OCTAVE_4, DURATION_QUARTER},
    { PITCH_F, OCTAVE_4, DURATION_HALF},

	/* ------------------ 13 ------------------ */
    { PITCH_REST, OCTAVE_3, DURATION_WHOLE },

	/* ------------------ 14 ------------------ */
    { PITCH_REST, OCTAVE_3, DURATION_WHOLE },

	/* ------------------ 15 ------------------ */
    { PITCH_DS, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_REST, OCTAVE_4, DURATION_EIGHTH},
    { PITCH_REST, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_AS, OCTAVE_4, DURATION_QUARTER},
    { PITCH_REST, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_REST, OCTAVE_5, DURATION_EIGHTH},
    { PITCH_FS, OCTAVE_4, DURATION_DOTTED_QUARTER},

	/* ------------------ 16 ------------------ */
    { PITCH_REST, OCTAVE_4, DURATION_HALF},
    { PITCH_REST, OCTAVE_4, DURATION_EIGHTH},
    { PITCH_F, OCTAVE_4, DURATION_EIGHTH},
};
const int part2_len = sizeof(part2_bass) / sizeof(part2_bass[0]);

// パート2：ベースライン
const ScoreNote part3_bass[] = {

	/* ------------------ 1 ------------------ */
    { PITCH_G, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_3, DURATION_EIGHTH },

    { PITCH_REST, OCTAVE_3, DURATION_QUARTER },
    { PITCH_G, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_3, DURATION_SIXTEENTH },
    { PITCH_G, OCTAVE_3, DURATION_SIXTEENTH },
    { PITCH_REST, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_A, OCTAVE_3, DURATION_EIGHTH },

	/* ------------------ 2 ------------------ */
	{ PITCH_REST, OCTAVE_3, DURATION_EIGHTH },

	{ PITCH_A, OCTAVE_3, DURATION_EIGHTH },

	{ PITCH_A, OCTAVE_3, DURATION_EIGHTH },
	{ PITCH_REST, OCTAVE_3, DURATION_EIGHTH },

	{ PITCH_A, OCTAVE_3, DURATION_EIGHTH },
	{ PITCH_REST, OCTAVE_3, DURATION_EIGHTH },

	{ PITCH_REST, OCTAVE_3, DURATION_QUARTER },

	/* ------------------ 3 ------------------ */
	{ PITCH_DS, OCTAVE_3, DURATION_EIGHTH },
	{ PITCH_REST, OCTAVE_3, DURATION_EIGHTH },

	{ PITCH_REST, OCTAVE_3, DURATION_EIGHTH },
	{ PITCH_DS, OCTAVE_3, DURATION_EIGHTH },
	{ PITCH_DS, OCTAVE_3, DURATION_EIGHTH },
	{ PITCH_REST, OCTAVE_3, DURATION_SIXTEENTH },
	{ PITCH_DS, OCTAVE_3, DURATION_SIXTEENTH },
	{ PITCH_REST, OCTAVE_3, DURATION_EIGHTH },
	{ PITCH_AS, OCTAVE_2, DURATION_EIGHTH },

	/* ------------------ 4 ------------------ */
	{ PITCH_REST, OCTAVE_2, DURATION_EIGHTH },
	{ PITCH_AS, OCTAVE_2, DURATION_EIGHTH },

	{ PITCH_AS, OCTAVE_2, DURATION_EIGHTH},
	{ PITCH_REST, OCTAVE_2, DURATION_EIGHTH},

	{ PITCH_AS, OCTAVE_2, DURATION_EIGHTH },
	{ PITCH_REST, OCTAVE_2, DURATION_SIXTEENTH },
	{ PITCH_FS, OCTAVE_3, DURATION_SIXTEENTH },
	{ PITCH_REST, OCTAVE_3, DURATION_QUARTER },

	/* ------------------ 5 ------------------ */
    { PITCH_G, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_3, DURATION_EIGHTH },

    { PITCH_REST, OCTAVE_3, DURATION_QUARTER },
    { PITCH_G, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_3, DURATION_SIXTEENTH },
    { PITCH_G, OCTAVE_3, DURATION_SIXTEENTH },
    { PITCH_REST, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_A, OCTAVE_3, DURATION_EIGHTH },

	/* ------------------ 6 ------------------ */
	{ PITCH_REST, OCTAVE_3, DURATION_EIGHTH },

	{ PITCH_A, OCTAVE_3, DURATION_EIGHTH },

	{ PITCH_A, OCTAVE_3, DURATION_EIGHTH },
	{ PITCH_REST, OCTAVE_3, DURATION_EIGHTH },

	{ PITCH_A, OCTAVE_3, DURATION_EIGHTH },
	{ PITCH_REST, OCTAVE_3, DURATION_EIGHTH },

	{ PITCH_REST, OCTAVE_3, DURATION_QUARTER },

	/* ------------------ 7 ------------------ */
	{ PITCH_DS, OCTAVE_3, DURATION_EIGHTH },
	{ PITCH_REST, OCTAVE_3, DURATION_EIGHTH },

	{ PITCH_REST, OCTAVE_3, DURATION_EIGHTH },
	{ PITCH_DS, OCTAVE_3, DURATION_EIGHTH },
	{ PITCH_DS, OCTAVE_3, DURATION_EIGHTH },
	{ PITCH_REST, OCTAVE_3, DURATION_SIXTEENTH },
	{ PITCH_DS, OCTAVE_3, DURATION_SIXTEENTH },
	{ PITCH_REST, OCTAVE_3, DURATION_EIGHTH },
	{ PITCH_AS, OCTAVE_2, DURATION_EIGHTH },

	/* ------------------ 8 ------------------ */
	{ PITCH_REST, OCTAVE_2, DURATION_EIGHTH },
	{ PITCH_AS, OCTAVE_2, DURATION_EIGHTH },

	{ PITCH_AS, OCTAVE_2, DURATION_EIGHTH},
	{ PITCH_REST, OCTAVE_2, DURATION_EIGHTH},

	{ PITCH_AS, OCTAVE_2, DURATION_EIGHTH },
	{ PITCH_REST, OCTAVE_2, DURATION_SIXTEENTH },
	{ PITCH_FS, OCTAVE_3, DURATION_SIXTEENTH },
	{ PITCH_REST, OCTAVE_3, DURATION_QUARTER },

	/* ------------------ 9 ------------------ */
    { PITCH_G, OCTAVE_2, DURATION_QUARTER },
    { PITCH_G, OCTAVE_3, DURATION_QUARTER },
    { PITCH_G, OCTAVE_2, DURATION_EIGHTH },
    { PITCH_G, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_G, OCTAVE_2, DURATION_EIGHTH },
    { PITCH_D, OCTAVE_2, DURATION_QUARTER },

	/* ------------------ 10 ------------------ */
    { PITCH_G, OCTAVE_2, DURATION_EIGHTH },
    { PITCH_D, OCTAVE_3, DURATION_QUARTER },
    { PITCH_D, OCTAVE_3, DURATION_QUARTER },
    { PITCH_D, OCTAVE_3, DURATION_QUARTER },

	/* ------------------ 11 ------------------ */
    { PITCH_DS, OCTAVE_2, DURATION_QUARTER },
    { PITCH_DS, OCTAVE_3, DURATION_QUARTER },
    { PITCH_DS, OCTAVE_2, DURATION_EIGHTH },
    { PITCH_DS, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_DS, OCTAVE_2, DURATION_EIGHTH },
    { PITCH_AS, OCTAVE_1, DURATION_QUARTER },

	/* ------------------ 12 ------------------ */
    { PITCH_AS, OCTAVE_1, DURATION_EIGHTH },
    { PITCH_AS, OCTAVE_2, DURATION_QUARTER },
    { PITCH_AS, OCTAVE_2, DURATION_QUARTER },
    { PITCH_FS, OCTAVE_3, DURATION_QUARTER },

	/* ------------------ 13 ------------------ */
    { PITCH_G, OCTAVE_2, DURATION_QUARTER },
    { PITCH_G, OCTAVE_3, DURATION_QUARTER },
    { PITCH_G, OCTAVE_2, DURATION_EIGHTH },
    { PITCH_G, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_G, OCTAVE_2, DURATION_EIGHTH },
    { PITCH_D, OCTAVE_2, DURATION_QUARTER },

	/* ------------------ 14 ------------------ */
    { PITCH_G, OCTAVE_2, DURATION_EIGHTH },
    { PITCH_D, OCTAVE_3, DURATION_QUARTER },
    { PITCH_D, OCTAVE_3, DURATION_QUARTER },
    { PITCH_D, OCTAVE_3, DURATION_QUARTER },

	/* ------------------ 15 ------------------ */
    { PITCH_DS, OCTAVE_2, DURATION_QUARTER },
    { PITCH_DS, OCTAVE_3, DURATION_QUARTER },
    { PITCH_DS, OCTAVE_2, DURATION_EIGHTH },
    { PITCH_DS, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_DS, OCTAVE_2, DURATION_EIGHTH },
    { PITCH_FS, OCTAVE_3, DURATION_QUARTER },

	/* ------------------ 16 ------------------ */
    { PITCH_CS, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_FS, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_CS, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_F, OCTAVE_3, DURATION_QUARTER },
    { PITCH_F, OCTAVE_3, DURATION_QUARTER },
};
const int part3_len = sizeof(part3_bass) / sizeof(part3_bass[0]);

const ScoreNote part4_bass[] = {

	/* ------------------ 1 ------------------ */
	{ PITCH_REST, OCTAVE_3, DURATION_HALF },
	{ PITCH_REST, OCTAVE_3, DURATION_QUARTER },
	{ PITCH_REST, OCTAVE_3, DURATION_EIGHTH },
	{ PITCH_D, OCTAVE_3, DURATION_EIGHTH },

	/* ------------------ 2 ------------------ */
	{ PITCH_REST, OCTAVE_3, DURATION_EIGHTH },

	{ PITCH_D, OCTAVE_3, DURATION_EIGHTH },

	{ PITCH_D, OCTAVE_3, DURATION_EIGHTH },
	{ PITCH_REST, OCTAVE_3, DURATION_EIGHTH },

	{ PITCH_D, OCTAVE_3, DURATION_EIGHTH },
	{ PITCH_REST, OCTAVE_3, DURATION_EIGHTH },

	{ PITCH_REST, OCTAVE_3, DURATION_QUARTER },

	/* ------------------ 3 ------------------ */
	{ PITCH_REST, OCTAVE_3, DURATION_WHOLE },

	/* ------------------ 4 ------------------ */
	{ PITCH_REST, OCTAVE_3, DURATION_WHOLE },

	/* ------------------ 5 ------------------ */
	{ PITCH_REST, OCTAVE_3, DURATION_HALF },
	{ PITCH_REST, OCTAVE_3, DURATION_QUARTER },
	{ PITCH_REST, OCTAVE_3, DURATION_EIGHTH },
	{ PITCH_D, OCTAVE_3, DURATION_EIGHTH },

	/* ------------------ 6 ------------------ */
	{ PITCH_REST, OCTAVE_3, DURATION_EIGHTH },

	{ PITCH_D, OCTAVE_3, DURATION_EIGHTH },

	{ PITCH_D, OCTAVE_3, DURATION_EIGHTH },
	{ PITCH_REST, OCTAVE_3, DURATION_EIGHTH },

	{ PITCH_D, OCTAVE_3, DURATION_EIGHTH },
	{ PITCH_REST, OCTAVE_3, DURATION_EIGHTH },

	{ PITCH_REST, OCTAVE_3, DURATION_QUARTER },

	/* ------------------ 7 ------------------ */
	{ PITCH_REST, OCTAVE_3, DURATION_WHOLE },

	/* ------------------ 8 ------------------ */
	{ PITCH_REST, OCTAVE_3, DURATION_WHOLE },

	/* ------------------ 9 ------------------ */
    { PITCH_REST, OCTAVE_2, DURATION_QUARTER },
    { PITCH_D, OCTAVE_3, DURATION_QUARTER },
    { PITCH_REST, OCTAVE_2, DURATION_EIGHTH },
    { PITCH_D, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_2, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_2, DURATION_QUARTER },

	/* ------------------ 10 ------------------ */
    { PITCH_REST, OCTAVE_2, DURATION_EIGHTH },
    { PITCH_A, OCTAVE_2, DURATION_QUARTER },
    { PITCH_D, OCTAVE_2, DURATION_QUARTER },
    { PITCH_D, OCTAVE_2, DURATION_QUARTER },

	/* ------------------ 11 ------------------ */
    { PITCH_REST, OCTAVE_2, DURATION_QUARTER },
    { PITCH_AS, OCTAVE_2, DURATION_QUARTER },
    { PITCH_REST, OCTAVE_2, DURATION_EIGHTH },
    { PITCH_AS, OCTAVE_2, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_2, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_1, DURATION_QUARTER },

	/* ------------------ 12 ------------------ */
    { PITCH_REST, OCTAVE_1, DURATION_EIGHTH },
    { PITCH_F, OCTAVE_2, DURATION_QUARTER },
    { PITCH_AS, OCTAVE_1, DURATION_QUARTER },
    { PITCH_FS, OCTAVE_2, DURATION_QUARTER },

	/* ------------------ 13 ------------------ */
    { PITCH_REST, OCTAVE_2, DURATION_QUARTER },
    { PITCH_D, OCTAVE_3, DURATION_QUARTER },
    { PITCH_REST, OCTAVE_2, DURATION_EIGHTH },
    { PITCH_D, OCTAVE_3, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_2, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_2, DURATION_QUARTER },

	/* ------------------ 14 ------------------ */
    { PITCH_REST, OCTAVE_2, DURATION_EIGHTH },
    { PITCH_A, OCTAVE_2, DURATION_QUARTER },
    { PITCH_D, OCTAVE_2, DURATION_QUARTER },
    { PITCH_D, OCTAVE_2, DURATION_QUARTER },

	/* ------------------ 15 ------------------ */
    { PITCH_REST, OCTAVE_2, DURATION_QUARTER },
    { PITCH_AS, OCTAVE_2, DURATION_QUARTER },
    { PITCH_REST, OCTAVE_2, DURATION_EIGHTH },
    { PITCH_AS, OCTAVE_2, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_2, DURATION_EIGHTH },
    { PITCH_FS, OCTAVE_2, DURATION_DOTTED_QUARTER },

	/* ------------------ 16 ------------------ */
    { PITCH_REST, OCTAVE_2, DURATION_EIGHTH },
    { PITCH_REST, OCTAVE_2, DURATION_QUARTER },
    { PITCH_F, OCTAVE_2, DURATION_QUARTER },
    { PITCH_F, OCTAVE_2, DURATION_QUARTER },
};
const int part4_len = sizeof(part4_bass) / sizeof(part4_bass[0]);
